In [1]:
import pandas as pd
#from pandas_profiling import ProfileReport

In [13]:

archivo21 = pd.read_csv('Data/Datos_proyecto_II_BI_2021.csv', delimiter=',', encoding='latin-1')
archivo17 = pd.read_csv('Data/Datos_proyecto_II_BI_2017.csv', delimiter=';', )
vs2archivo21 = pd.read_csv('Data/Datos_proyecto_II_BI_2021 filtrado.csv', delimiter=',', encoding='latin-1' )
vs2archivo17 = pd.read_csv('Data/Datos_proyecto_II_BI_2017 filtrado.csv', delimiter=',', )
#report = ProfileReport(archivo)
#report.to_file("exploracion.html")


/var/folders/55/n7y8ldr92dv_vfrc7rqcbbgw0000gn/T/ipykernel_992/1910272272.py:1: DtypeWarning: Columns (334,410,412,540,541,543,545,549,552,553,554,555,556,557) have mixed types. Specify dtype option on import or set low_memory=False.
  archivo21 = pd.read_csv('Data/Datos_proyecto_II_BI_2021.csv', delimiter=',', encoding='latin-1')
/var/folders/55/n7y8ldr92dv_vfrc7rqcbbgw0000gn/T/ipykernel_992/1910272272.py:2: DtypeWarning: Columns (123,145,231,295,297,380,381,383,398,402,469,481,488,495,496,499,500,501,508,509,510,511) have mixed types. Specify dtype option on import or set low_memory=False.
  archivo17 = pd.read_csv('Data/Datos_proyecto_II_BI_2017.csv', delimiter=';', )


In [3]:
# Asegúrate de cargar tus DataFrames aquí con pd.read_csv o la función que corresponda.
# archivo21 = pd.read_csv('tu_ruta_de_archivo_21.csv')
# archivo17 = pd.read_csv('tu_ruta_de_archivo_17.csv')

def filtrar_variables_con_variabilidad(df, threshold=0.9):
    # Identificamos las columnas donde el valor más común es menor o igual al 90%
    vars_to_keep = [col for col in df.columns if df[col].value_counts(normalize=True).max() <= threshold]
    return df[vars_to_keep]

# Aplicamos la función a tus DataFrames
archivo21_filtrado = filtrar_variables_con_variabilidad(archivo21)
archivo17_filtrado = filtrar_variables_con_variabilidad(archivo17)


In [23]:
archivo17_filtrado.to_csv('Data/Datos_proyecto_II_BI_2017 filtrado 300.csv', index=False)
archivo21_filtrado.to_csv('Data/Datos_proyecto_II_BI_2021 filtrado 300.csv', index=False)

In [36]:
#organizar los nombres de las columnas en un diccionario
# las que comiencen con "NHC", se ingresaran en una lista de columnas como valor con la letra inmediatamente contigua a "NHC" como llave. 
# Por ejemplo, para una columna llamada "NHCBP1", se ingresará al diccionario como "B": ["NHCBP1", "NHCBP2", "NHCBP3", ...]
# Para las columnas que comiencen con "NPC", se ingresaran en una lista de columnas como valor con la letra inmediatamente contigua a "NPC" como llave.
# Por ejemplo, para una columna llamada "NPCHP1", se ingresará al diccionario como "H": ["NHPP1", "NHPP2", "NHPP3", ...]
# Para las columnas que no cumplan ninguna de las condiciones anteriores, se ingresaran en una lista de columnas como valor con la letra "otros" como llave.
# Para las columnas que comiencen con "NVC", se ingresaran en una lista de columnas como valor con la letra inmediatamente contigua a "NVC" como llave.
# Por ejemplo, para una columna llamada "NVCHP1", se ingresará al diccionario como "H": ["NVCHP1", "NVCHP2", "NVCHP3", ...]
def organizar_columnas(df):
    columnas = df.columns
    columnas_dict = {}
    for columna in columnas:
        if columna.startswith("NHC"):
            letra = columna[3]
            if letra in columnas_dict:
                columnas_dict[letra].append(columna)
            else:
                columnas_dict[letra] = [columna]
        elif columna.startswith("NPC"):
            letra = columna[3]
            if letra in columnas_dict:
                columnas_dict[letra].append(columna)
            else:
                columnas_dict[letra] = [columna]
        elif columna.startswith("NVC"):
            letra = columna[3]
            if letra in columnas_dict:
                columnas_dict[letra].append(columna)
            else:
                columnas_dict[letra] = [columna]
        else:
            if "otros" in columnas_dict:
                columnas_dict["otros"].append(columna)
            else:
                columnas_dict["otros"] = [columna]
    return columnas_dict

In [38]:
# Aplicamos la función a tus DataFrames
columnas_ordenadas21 = organizar_columnas(archivo21_filtrado)
columnas_ordenadas17 = organizar_columnas(archivo17_filtrado)



In [39]:
print(columnas_ordenadas21.keys())

dict_keys(['otros', 'B', 'C', 'D', 'E', 'F', 'H'])


In [79]:
print(columnas_ordenadas21["H"])


['NPCHP2', 'NPCHP3', 'NPCHP4', 'NPCHP4A', 'NPCHP5', 'NPCHP6', 'NPCHP6A', 'NPCHP7', 'NPCHP10', 'NPCHP10A', 'NPCHP11A', 'NPCHP12', 'NPCHP13A', 'NPCHP13B', 'NPCHP14', 'NPCHP16', 'NPCHP17', 'NPCHP18AI', 'NPCHP18AO', 'NPCHP19', 'NPCHP20', 'NPCHP20A', 'NPCHP20B', 'NPCHP21A', 'NPCHP21AA', 'NPCHP21B', 'NPCHP21BA', 'NPCHP21CA', 'NPCHP21DA', 'NPCHP22', 'NPCHP22A', 'NPCHP24AA', 'NPCHP24AB', 'NPCHP24BA', 'NPCHP24BB', 'NPCHP28A', 'NPCHP28B', 'NPCHP30A', 'NPCHP30G', 'NPCHP30I', 'NPCHP30J', 'NPCHP30L', 'NPCHP31AA', 'NPCHP31AB', 'NPCHP31BA', 'NPCHP31BB', 'NPCHP31CA', 'NPCHP31CB', 'NPCHP31DA', 'NPCHP31DB', 'NPCHP31DA_1', 'NPCHP31GA', 'NPCHP31GB', 'NPCHP31DA_2', 'NPCHP31DB_2', 'NPCHP32', 'NPCHP32A', 'NPCHP33', 'NPCHP34', 'NPCHP36A', 'NPCHP37']


['NPCHP2', 'NPCHP3', 'NPCHP4', 'NPCHP4A', 'NPCHP5', 'NPCHP6', 'NPCHP6A', 'NPCHP7', 'NPCHP10', 'NPCHP10A', 'NPCHP11A', 'NPCHP12', 'NPCHP13A', 'NPCHP13B', 'NPCHP14', 'NPCHP16', 'NPCHP17', 'NPCHP18AI', 'NPCHP18AO', 'NPCHP19', 'NPCHP20', 'NPCHP20A', 'NPCHP20B', 'NPCHP21A', 'NPCHP21AA', 'NPCHP21B', 'NPCHP21BA', 'NPCHP21CA', 'NPCHP21DA', 'NPCHP22', 'NPCHP22A', 'NPCHP24AA', 'NPCHP24AB', 'NPCHP24BA', 'NPCHP24BB', 'NPCHP28A', 'NPCHP28B', 'NPCHP30A', 'NPCHP30G', 'NPCHP30I', 'NPCHP30J', 'NPCHP30L', 'NPCHP31AA', 'NPCHP31AB', 'NPCHP31BA', 'NPCHP31BB', 'NPCHP31CA', 'NPCHP31CB', 'NPCHP31DA', 'NPCHP31DB', 'NPCHP31DA_1', 'NPCHP31GA', 'NPCHP31GB', 'NPCHP31DA_2', 'NPCHP31DB_2', 'NPCHP32', 'NPCHP32A', 'NPCHP33', 'NPCHP34', 'NPCHP36A', 'NPCHP37']


dics: c, f, h, b
nodics: d, e

In [6]:
archivo17.info()
print('------------------------------------')
archivo21.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4727 entries, 0 to 4726
Columns: 552 entries, Column1 to NPCHP35I
dtypes: float64(324), int64(164), object(64)
memory usage: 19.9+ MB
------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8630 entries, 0 to 8629
Columns: 601 entries, Unnamed: 0 to NPCHP37
dtypes: float64(391), int64(191), object(19)
memory usage: 39.6+ MB


In [7]:
archivo17_filtrado.info()
print('------------------------------------')
archivo21_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4727 entries, 0 to 4726
Columns: 308 entries, Column1 to NPCHP35I
dtypes: float64(156), int64(106), object(46)
memory usage: 11.1+ MB
------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8630 entries, 0 to 8629
Columns: 374 entries, Unnamed: 0 to NPCHP37
dtypes: float64(257), int64(114), object(3)
memory usage: 24.6+ MB


In [22]:
# imprimir valores unicos, con el numero de apariciones y el porcentaje de apariciones para el df vs2archivo21
def imprimir_valores_unicos(df):
    for col in df.columns:
        print(df[col].value_counts(normalize=True))
        print('------------------------------------')
imprimir_valores_unicos(vs2archivo21)

Unnamed: 0
0       0.000116
5748    0.000116
5762    0.000116
5761    0.000116
5760    0.000116
          ...   
2871    0.000116
2870    0.000116
2869    0.000116
2868    0.000116
8629    0.000116
Name: proportion, Length: 8630, dtype: float64
------------------------------------
MPIO
11001    0.838702
25175    0.013905
25473    0.013094
25214    0.012514
25286    0.012283
25377    0.011472
25290    0.010081
25758    0.008459
25430    0.008459
25754    0.007879
25269    0.007764
25785    0.007648
25126    0.007184
25099    0.006837
25899    0.005678
25769    0.005330
25817    0.004635
25260    0.004403
25295    0.004403
25799    0.003824
25740    0.003244
25898    0.002202
Name: proportion, dtype: float64
------------------------------------
COD_LOCALIDAD
11.0    0.118127
8.0     0.109146
10.0    0.076126
19.0    0.068804
1.0     0.062586
9.0     0.060652
18.0    0.058856
13.0    0.058027
7.0     0.055264
4.0     0.054711
5.0     0.047251
3.0     0.040066
16.0    0.038823
2.0     0.03

In [20]:
vs2archivo21.info()
# valores unicos de cada columna porcentaje
print('------------------------------------')
vs2archivo21.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8630 entries, 0 to 8629
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        8630 non-null   int64  
 1   MPIO              8630 non-null   int64  
 2   COD_LOCALIDAD     7238 non-null   float64
 3   NOMBRE_LOCALIDAD  7238 non-null   object 
 4   NPCEP17           8630 non-null   int64  
 5   NPCEP4            8630 non-null   int64  
 6   NPCEP5            8630 non-null   int64  
 7   NVCBP8B           8630 non-null   int64  
 8   NVCBP8H           8630 non-null   int64  
 9   NVCBP11AA         8616 non-null   float64
dtypes: float64(2), int64(7), object(1)
memory usage: 674.3+ KB
------------------------------------


Unnamed: 0          8630
MPIO                  22
COD_LOCALIDAD         20
NOMBRE_LOCALIDAD      20
NPCEP17                4
NPCEP4               105
NPCEP5                 2
NVCBP8B                3
NVCBP8H                3
NVCBP11AA              9
dtype: int64

In [ ]:
def splitear(texto):
    return texto.split(' ')


In [65]:
def obtener_columnas_ordenadas21(dictA, listA):
    nuevo_dic = {}

    for i in listA:
        if i in dictA:
            nuevo_dic[i] = dictA[i]
    return nuevo_dic

In [81]:
textoB = {
    "NVCBP1": "1. La vía de acceso a la edificación es:",
    "NVCBP2": "2. ¿Cuál es el estado de la vía?",
    "NVCBP3": "3. ¿La edificación donde está ubicada la vivienda tiene andén?",
    "NVCBP4": "4. ¿La edificación está ubicada en un conjunto residencial?",
    "NVCBP5": "5. La iluminación de la vía de acceso a la edificación en las noches es:",
    "NVCBP6": "6. ¿Cuántos pisos tiene la edificación donde está ubicada la vivienda?",
    "NVCBP7": "7. ¿La edificación donde está ubicada la vivienda tiene ascensor?",
    "NVCBP8A": "8. ¿La vivienda presenta: 1. Humedades en el techo o en las paredes?",
    "NVCBP8B": "8. ¿La vivienda presenta: 2. Goteras en el techo?",
    "NVCBP8C": "8. ¿La vivienda presenta: 3. Grietas en techos y paredes?",
    "NVCBP9": "9. ¿Algún espacio de la vivienda está dedicado a negocios de industria, comercio o servicios?",
    "NVCBP9A1": "¿A qué negocio se dedica este espacio: 1. Comercio?",
    "NVCBP9A2": "¿A qué negocio se dedica este espacio: 2. Industria?",
    "NVCBP9A3": "¿A qué negocio se dedica este espacio: 3. Servicios?",
    "NVCBP10": "10. Tipo de vivienda:",
    "NVCBP11AA": "Estrato para tarifa:",
    "NVCBP13": "13. ¿Cuál es el material predominante de los pisos?",
    "NVCBP14A": "14. La vivienda está cerca de: 1. Fábricas o industrias",
    "NVCBP14B": "14. La vivienda está cerca de: 2. Basureros o botaderos de basuras",
    "NVCBP14E": "14. La vivienda está cerca de: 5. Bares o discotecas",
    "NVCBP14F": "14. La vivienda está cerca de: 7. Expendios de droga (ollas)",
    "NVCBP14G": "14. La vivienda está cerca de: 8. Lotes baldíos o sitios oscuros y peligrosos",
    "NVCBP14I": "14. La vivienda está cerca de: 10. Caños de aguas residuales",
    "NVCBP14K": "14. La vivienda está cerca de: 12. Talleres de mecánica, servitecas o estaciones de gasolina",
    "NVCBP15A": "15. ¿Cuáles de los siguientes problemas presenta el entorno donde está ubicada su vivienda? 1. Ruido",
    "NVCBP15B": "15. ¿Cuáles de los siguientes problemas presenta el entorno donde está ubicada su vivienda?: 2. Exceso de anuncios publicitarios",
    "NVCBP15C": "15. ¿Cuáles de los siguientes problemas presenta el entorno donde está ubicada su vivienda?: 3. Inseguridad",
    "NVCBP15D": "15. ¿Cuáles de los siguientes problemas presenta el entorno donde está ubicada su vivienda?: 4. Contaminación del aire",
    "NVCBP15E": "15. ¿Cuáles de los siguientes problemas presenta el entorno donde está ubicada su vivienda?: 5. Malos olores",
    "NVCBP15F": "15. ¿Cuáles de los siguientes problemas presenta el entorno donde está ubicada su vivienda?: 6. Disposición inadecuada de las basuras",
    "NVCBP15G": "15. ¿Cuáles de los siguientes problemas presenta el entorno donde está ubicada su vivienda?: 7. Invasión del espacio público (andenes, calles, parques¿..)",
    "NVCBP15H": "15. ¿Cuáles de los siguientes problemas presenta el entorno donde está ubicada su vivienda?: 8. Presencia de insectos, roedores o animales que causen molestia",
    "NVCBP15I": "15. ¿Cuáles de los siguientes problemas presenta el entorno donde está ubicada su vivienda?: 9. Contaminación de cuerpos de agua (ríos, caños, humedales, lagunas)",
    "NVCBP15J": "15. ¿Cuáles de los siguientes problemas presenta el entorno donde está ubicada su vivienda?: 10. Abandono de escombros",
    "NVCBP16A1": "16. Considera que el entorno donde esta ubicada su vivienda tiene condiciones adecuadas para la movilidad de: 1. Personas con discapacidad visual?",
    "NVCBP16A2": "16. Considera que el entorno donde esta ubicada su vivienda tiene condiciones adecuadas para la movilidad de: 2. Personas con discapacidad para caminar?",
    "NVCBP16A3": "16. Considera que el entorno donde esta ubicada su vivienda tiene condiciones adecuadas para la movilidad de: 3. Adultos mayores?",
    "NVCBP16A4": "16. Considera que el entorno donde esta ubicada su vivienda tiene condiciones adecuadas para la movilidad de: 4. Personas con bebes o niños menores de 5 años?"
}


In [61]:
dictC = {
    "NHCCP1": "1. La vivienda ocupada por este hogar es:",
    "NHCCP2": "2. ¿Cuál es el valor MENSUAL de la cuota?",
    "NHCCP3": "3. ¿Alguna persona de este hogar tiene escritura registrada de esta vivienda?",
    "NHCCP4A": "4. La escritura está a nombre de: 1 Jefe(a) del hogar",
    "NHCCP4B": "4. La escritura está a nombre de: 2 Cónyuge",
    "NHCCP4C": "4. La escritura está a nombre de: 3 Hijos varones que vivan en este hogar",
    "NHCCP4D": "4. La escritura está a nombre de: 4 Hijas mujeres que vivan en este hogar",
    "NHCCP4E": "4. La escritura está a nombre de: 5 Otras personas del hogar",
    "NHCCP5": "5. Si fuera a comprar esta vivienda ahora, ¿cuánto cree que tendría que pagar?",
    "NHCCP6": "6. ¿Cuál fue el año de compra de la vivienda o del lote o terreno?",
    "NHCCP7": "7. ¿Cuál fue el valor de la compra?",
    "NHCCP8_1": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 1. Crédito bancario hipotecario",
    "NHCCP8_2": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 2. Crédito bancario diferente a hipotecario",
    "NHCCP8_3": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 3. Crédito con el Fondo Nacional deI Ahorro",
    "NHCCP8_4": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 4. Crédito con cooperativas o fondos de empleados",
    "NHCCP8_5": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 5. Crédito con fondos de vivienda o cajas de vivienda",
    "NHCCP8_6": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 6. Préstamos de amigos o familiares",
    "NHCCP8_7": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 7. Cesantías",
    "NHCCP8_8": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 8. Recursos propios o ahorros",
    "NHCCP8_9": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 9. Subsidios",
    "NHCCP8_10": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 10. Otra",
    "NHCCP9": "9. Si tuviera que pagar arriendo por esta vivienda, ¿cuánto cree que sería el monto MENSUAL?",
    "NHCCP10": "10. ¿Cuánto paga MENSUALMENTE por el arriendo o leasing de esta vivienda?",
    "NHCCP10A": "10a. ¿Cuenta con contrato escrito de arrendamiento?",
    "NHCCP10B": "10b. ¿A raíz de las medidas tomadas por la pandemia del coronavirus (Covid-19), entre marzo de 2020 y el momento actual: 1. Se atrasó o dejo de pagar alguna cuota de arrendamiento?",
    "NHCCP10C": "¿Cuántas dejó de pagar?",
    "NHCCP10D": "10b. ¿A raíz de las medidas tomadas por la pandemia del coronavirus (Covid-19), entre marzo de 2020 y el momento actual: 2. El arrendatario le dio algún descuento en la cuota de arrendamiento?",
    "NHCCP10E": "1. ¿En total cuanto suman todos los descuentos que le hicieron?",
    "NHCCP11": "11. En los PRÓXIMOS 2 AÑOS, ¿usted o alguna persona de este hogar tiene planes de adquirir vivienda?",
    "NHCCP11A": "¿Principalmente por qué motivo planea comprar?",
    "NHCCP12": "12. ¿Cuál es la razón principal para no tener planes de adquirir vivienda?",
    "NHCCP13A": "13. ¿Cuáles de las siguientes fuentes de financiamiento piensan utilizar para la compra de esta vivienda?: 1. Crédito bancario hipotecario",
    "NHCCP13B": "13. ¿Cuáles de las siguientes fuentes de financiamiento piensan utilizar para la compra de esta vivienda?: 2. Crédito bancario diferente a hipotecario",
    "NHCCP13C": "13. ¿Cuáles de las siguientes fuentes de financiamiento piensan utilizar para la compra de esta vivienda?: 3. Crédito con el Fondo Nacional deI Ahorro",
    "NHCCP13D": "13. ¿Cuáles de las siguientes fuentes de financiamiento piensan utilizar para la compra de esta vivienda?: 4. Crédito con cooperativas o fondos de empleados",
    "NHCCP13E": "13. ¿Cuáles de las siguientes fuentes de financiamiento piensan utilizar para la compra de esta vivienda?: 5. Crédito con fondos de vivienda o cajas de vivienda",
    "NHCCP13F": "13. ¿Cuáles de las siguientes fuentes de financiamiento piensan utilizar para la compra de esta vivienda?: 6. Préstamos de amigos o familiares",
    "NHCCP13G": "13. ¿Cuáles de las siguientes fuentes de financiamiento piensan utilizar para la compra de esta vivienda?: 7. Cesantías",
    "NHCCP13H": "13. ¿Cuáles de las siguientes fuentes de financiamiento piensan utilizar para la compra de esta vivienda?: 8. Recursos propios o ahorros",
    "NHCCP13I": "13. ¿Cuáles de las siguientes fuentes de financiamiento piensan utilizar para la compra de esta vivienda?: 9. Subsidios",
    "NHCCP13J": "13. ¿Cuáles de las siguientes fuentes de financiamiento piensan utilizar para la compra de esta vivienda?: 10. Otra",
    "NHCCP14": "14. ¿Este hogar paga MENSUALMENTE cuota de administración o celaduría?",
    "NHCCP14A": "14. ¿Este hogar paga MENSUALMENTE cuota de administración o celaduría? Valor",
    "NHCCP15": "15. En los ÚLTIMOS 36 MESES, ¿alguna persona de este hogar recibió subsidio en dinero o en especie del gobierno o de otra institución para la compra, construcción, mejora o escrituración de vivienda o lote?:",
    "NHCCP15A": "15. En los ÚLTIMOS 36 MESES, ¿alguna persona de este hogar recibió subsidio en dinero o en especie del gobierno o de otra institución para la compra, construcción, mejora o escrituración de vivienda o lote?: $ ¿Cuánto recibieron?",
    "NHCCPCTRL2": "16. ¿Cuántas personas componen este hogar?",
    "NHCCP19": "17. Incluyendo sala y comedor, ¿de cuántos cuartos o piezas dispone este hogar? (excluya cocina, baños, garajes y los cuartos destinados a negocio)",
    "NHCCP19A": "¿Cuántos de estos cuartos reciben iluminación natural?",
    "NHCCP20": "18. ¿En cuántos de esos cuartos duermen las personas del hogar?",
    "NHCCP22A": "19. Este hogar dispone de: Jardín o patio",
    "NHCCP22B": "19. Este hogar dispone de: Lote o solar",
    "NHCCP22C": "19. Este hogar dispone de: Garaje o sitio de parqueo",
    "NHCCP22D": "19. Este hogar dispone de: Azotea o terraza",
    "NHCCP22E": "19. Este hogar dispone de: Otras zonas comunes (pasillos, escaleras, salón comunal...)",
    "NHCCP23": "20. ¿En dónde preparan los alimentos las personas de este hogar?",
    "NHCCP24": "21. ¿El hogar cuenta con una cocina o espacio destinado exclusivamente para preparar alimentos?",
    "NHCCP25": "22. La cocina o sitio para preparar alimentos es:",
    "NHCCP26": "23. ¿Qué energía o combustible utilizan principalmente para cocinar?",
    "NHCCP26A": "24. ¿Cuánto pagaron EL MES PASADO en combustible para cocinar? Valor",
    "NHCCP27": "25. El agua para preparar los alimentos (o beber) la obtienen principalmente de:",
    "NHCCP28": "26. ¿El agua llega al hogar todos los 7 días de la semana?",
    "NHCCP28A": "¿Cuántos días a la semana llega?",
    "NHCCP29": "27. ¿El suministro es continuo las 24 horas, los días que llega el agua?",
    "NHCCP29A": "¿Cuántas horas al día llega?",
    "NHCCP31": "28. ¿Con qué tipo de servicio sanitario cuenta el hogar?",
    "NHCCP32": "29. ¿De cuántos servicios sanitarios o inodoros dispone este hogar?",
    "NHCCP33": "30. El servicio sanitario está ubicado:",
    "NHCCP34": "31. El servicio sanitario es:",
    "NHCCP35": "32. Este hogar dispone de:",
    "NHCCP35A": "¿Cuantos cuartos?",
    "NHCCP36A": "33. Este hogar dispone de: 1. Lavamanos",
    "NHCCP36B": "33. Este hogar dispone de: 2. Lavadero",
    "NHCCP36C": "33. Este hogar dispone de: 3. Tanque de reserva de agua",
    "NHCCP37": "34. ¿Cómo eliminan principalmente la basura en este hogar?",
    "NHCCP38": "35. ¿En este hogar clasifican los residuos?",
    "NHCCP38AA": "¿Qué tipo de residuos separa: 1. Orgánicos: vegetales y restos de comida",
    "NHCCP38AB": "¿Qué tipo de residuos separa: 2. Vidrio",
    "NHCCP38AC": "¿Qué tipo de residuos separa: 3. Papel y cartón",
    "NHCCP38AD": "¿Qué tipo de residuos separa: 4. Empaques y envases plásticos",
    "NHCCP38AF": "¿Qué tipo de residuos separa: 5. Metales (latas, ollas, rejas, alambres, herramientas)",
    "NHCCP38AG": "¿Qué tipo de residuos separa: 6. Otros (medicamentos, pilas, bombillas u otros)",
    "NHCCP38B": "¿Cuál es la razón principal por la que no separa los residuos?",
    "NHCCP39A": "36. ¿Cuáles de las siguientes prácticas realiza este hogar para reducir el consumo de agua y energía eléctrica?: 1. Usar luminarias o bombillas de bajo consumo (LED)",
    "NHCCP39B": "36. ¿Cuáles de las siguientes prácticas realiza este hogar para reducir el consumo de agua y energía eléctrica?: 2. Apagar luces",
    "NHCCP393": "36. ¿Cuáles de las siguientes prácticas realiza este hogar para reducir el consumo de agua y energía eléctrica?: 3. Planchar la mayor cantidad de ropa en cada ocasión o no planchar",
    "NHCCP39C": "36. ¿Cuáles de las siguientes prácticas realiza este hogar para reducir el consumo de agua y energía eléctrica?: 4. Cambiar electrodomésticos por otros de bajo consumo",
    "NHCCP39D": "36. ¿Cuáles de las siguientes prácticas realiza este hogar para reducir el consumo de agua y energía eléctrica?: 5. Desconectar aparatos eléctricos cuando no los usan",
    "NHCCP39E": "36. ¿Cuáles de las siguientes prácticas realiza este hogar para reducir el consumo de agua y energía eléctrica?: 6. Reutilizar agua de la ducha, lavado de ropa, lavamanos y lavaplatos",
    "NHCCP39F": "36. ¿Cuáles de las siguientes prácticas realiza este hogar para reducir el consumo de agua y energía eléctrica?: 7. Recolectar agua lluvia",
    "NHCCP39G": "36. ¿Cuáles de las siguientes prácticas realiza este hogar para reducir el consumo de agua y energía eléctrica?: 8. Usar tanque sanitario de bajo consumo de agua",
    "NHCCP399": "36. ¿Cuáles de las siguientes prácticas realiza este hogar para reducir el consumo de agua y energía eléctrica?: 9. Instalaron accesorios ahorradores de agua en duchas, lavamanos y lavaplatos",
    "NHCCP40A": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 1. Máquina lavadora de ropa",
    "NHCCP40B": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 2. Nevera o refrigerador",
    "NHCCP40C": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 3. Estufa eléctrica o a gas",
    "NHCCP40D": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 4. Horno eléctrico o a gas",
    "NHCCP40E": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 5. Horno microondas",
    "NHCCP40F": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 6. Calentador de agua eléctrico o de gas o ducha eléctrica",
    "NHCCP40G": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 7. Televisor convencional a color",
    "NHCCP40H": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 8. Televisor LCD, Plasma, LED",
    "NHCCP40I": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 9. Consola de videojuegos",
    "NHCCP40J": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 10. Reproductor de video (DVD, Blu Ray)",
    "NHCCP40K": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 11. Equipo de sonido o minicomponente",
    "NHCCP40L": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 12. Bienes raíces diferentes a la vivienda que habita",
    "NHCCP40M": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 13. Maquinaria",
    "NHCCP40N": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 14. Animales de cría",
    "NHCCP40O": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 15. Títulos valor",
    "NHCCP40P": "37. ¿Cuáles de los siguientes bienes o activos posee este hogar?: 16. Vehículos diferentes a carro particular",
    "NHCCP41": "38. ¿Las personas de este hogar poseen carro particular?",
    "NHCCP41A": "¿Cuántos?",
    "NHCCP41B": "¿Cuántos se utilizan como herramienta de trabajo?",
    "NHCCP42": "39. ¿El (los) vehículo(s) está(n) matriculado(s) en este municipio?",
    "NHCCP42A": "¿Cuántos?",
    "NHCCP44": "40. ¿Las personas de este hogar poseen motocicleta?",
    "NHCCP44A": "¿Cuántas?",
    "NHCCP44B": "¿Cuántas se utilizan como herramienta de trabajo?",
    "NHCCP45": "41. ¿Las personas de este hogar poseen bicicleta?",
    "NHCCP45A": "¿Cuántas?",
    "NHCCP45B": "¿Cuántas se utilizan como medio de transporte para ir a trabajar, estudiar, hacer diligencias o visitar familiares y amigos?",
    "NHCCP41_A": "41a. ¿En el ÚLTIMO AÑO algún miembro de este hogar: 1. Ha tenido accidentes transportándose en bicicleta?",
    "NHCCP41_B": "41a. ¿En el ÚLTIMO AÑO algún miembro de este hogar: 2. Ha sido víctima de robo de su bicicleta?",
    "NHCCP46A": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 1. Estación TransMilenio o paradero alimentador (solo para Bogotá y Soacha). Minutos",
    "NHCCP46B": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 2. Paradero buses del SITP (solo para Bogotá y Soacha). Minutos",
    "NHCCP46C": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 3. Paradero de transporte público (buses, busetas o colectivos). Minutos",
    "NHCCP46D": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 4. Paradero de transporte intermunicipal. Minutos",
    "NHCCP46E": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 5. Parque o zonas verdes. Minutos",
    "NHCCP46F": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 6. Tienda o supermercado. Minutos",
    "NHCCP46G": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 7. Droguería o farmacia. Minutos",
    "NHCCP46H": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 8. Banco o cajero. Minutos",
    "NHCCP46I": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 9. CAI o estación de policía. Minutos",
    "NHCCP46J": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 10. Biblioteca. Minutos",
    "NHCCP46K": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 11. Escenarios culturales o recreativos. Minutos",
    "NHCCP46L": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 12. Cicloruta. Minutos",
    "NHCCP46M": "42. ¿Cuánto tiempo gastan caminando, en promedio, las personas de este hogar para llegar a los siguientes servicios o establecimientos más cercanos a la vivienda?: 13. Centro médico. Minutos",
    "NHCCP47A": "43. ¿En este hogar tienen mascotas que vivan permanentemente con los miembros del hogar? 1. Perros",
    "NHCCP47A1": "43. ¿En este hogar tienen mascotas que vivan permanentemente con los miembros del hogar? 1. Perros ¿Cuántos?",
    "NHCCP47B": "43. ¿En este hogar tienen mascotas que vivan permanentemente con los miembros del hogar? 2. Gatos",
    "NHCCP47B1": "43. ¿En este hogar tienen mascotas que vivan permanentemente con los miembros del hogar? 2. Gatos ¿Cuántos?",
    "NHCCP47C": "43. ¿En este hogar tienen mascotas que vivan permanentemente con los miembros del hogar? 3. Otros"


    
}



In [80]:
textoD = {
    "NHCDP2": "2. ¿Cuánto pagó este hogar la ÚLTIMA VEZ por el servicio de acueducto? Valor $",
    "NHCDP2A": "¿A cuántos meses correspondió el pago?",
    "NHCDP3": "3. ¿Este hogar paga por el servicio de alcantarillado?",
    "NHCDP4": "4. ¿Cuánto pagó este hogar la ÚLTIMA VEZ por el servicio de alcantarillado? Valor $",
    "NHCDP4A": "¿A cuántos meses correspondió el pago?",
    "NHCDP5": "5. ¿Este hogar paga por el servicio de recolección de basuras?",
    "NHCDP6": "6. ¿Cuánto pagó este hogar la ÚLTIMA VEZ por el servicio de recolección de basuras? Valor $",
    "NHCDP6A": "¿A cuántos meses correspondió el pago?",
    "NHCDP7": "7. ¿Los servicios de acueducto, alcantarillado y recolección de basuras (aseo) los pagan entre varios hogares de esta u otras viviendas?",
    "NHCDP7A": "¿Entre cuántos hogares?",
    "NHCDP10": "10. ¿El servicio de energía lo pagan entre varios hogares de esta u otras viviendas?",
    "NHCDP10A": "¿Entre cuántos hogares?",
    "NHCDP11": "11. ¿Cuánto pagó este hogar la ÚLTIMA VEZ por el servicio de energía eléctrica? Valor $",
    "NHCDP13": "13. ¿Durante los ÚLTIMOS 30 DÍAS se han presentado cortes o suspensiones del servicio?",
    "NHCDP15": "15. ¿Este hogar tiene servicio de gas natural conectado a red pública?",
    "NHCDP17": "17. ¿El servicio de gas natural lo pagan entre varios hogares de esta u otras viviendas?",
    "NHCDP17A": "¿Entre cuántos hogares?",
    "NHCDP18": "18. ¿Cuánto pagó este hogar la ÚLTIMA VEZ por el servicio de gas natural? Valor $",
    "NHCDP20": "20. En los ÚLTIMOS 24 MESES, ¿han realizado la Revisión Técnica Reglamentaria (RTR)?",
    "NHCDP21": "21. ¿Este hogar tiene servicio telefónico fijo?",
    "NHCDP23": "23. ¿Cuánto pagó este hogar la ÚLTIMA VEZ por el servicio telefónico fijo?",
    "NHCDP24": "24. ¿En este hogar tienen computador de mesa o de escritorio (PC - Desktop)?",
    "NHCDP24A": "¿Cuántos?",
    "NHCDP26": "26. ¿En este hogar tienen tabletas digitales (tablets)?",
    "NHCDP26A": "¿Cuántas?",
    "NHCDP27": "27. ¿El hogar tiene conexión a internet?",
    "NHCDP27B": "2. Móvil",
    "NHCDP28": "28. ¿Este hogar paga por el servicio de internet?",
    "NHCDP29": "29. ¿Cuánto pagó este hogar la ÚLTIMA VEZ por el servicio de internet? Valor $",
    "NHCDP30A": "Señal abierta: 1. Análoga",
    "NHCDP30B": "Señal abierta: 2. TDT",
    "NHCDP32": "32. ¿Cuánto pagó este hogar la ÚLTIMA VEZ por el servicio de televisión? Valor $"
}


In [82]:
textoE = {
    "NPCEP4": "4. ¿Cuántos años cumplidos tiene ... ?",
    "NPCEP5": "5. Sexo:",
    "NPCEP6": "6. ¿Cuál es el parentesco de ... con el o la jefe(a) de este hogar?",
    "NPCEP7": "7. ¿Cuál es el estado civil actual de ... ?",
    "NPCEP8A": "Núm. de orden",
    "NPCEP9": "9. ¿Dónde vivía la madre de ... cuando ... nació?",
    "NPCEP9A": "Departamento",
    "NPCEP9B": "Municipio",
    "NPCEP10": "10. ¿La madre de ... en ese momento vivía en?:",
    "NPCEP11A": "11.¿Donde nació ...?",
    "NPCEP11AA": "Departamento",
    "NPCEP11AB": "Municipio",
    "NPCEP11": "12. ¿ ... siempre ha vivido en este municipio?",
    "NPCEP13": "13.¿Dónde vivía ... hace 5 años?",
    "NPCEP13A": "Departamento",
    "NPCEP13B": "Municipio",
    "NPCEP15": "15. ¿Cuál fue la principal razón para venir a este municipio?",
    "NPCEP21A": "Núm. de orden",
    "NPCEP22": "23. ¿Cuál es o fue el nivel de educación más alto alcanzado por el padre de ... ?",
    "NPCEP22A": "Cuántos años aprobados:",
    "NPCEP24": "24. ¿La madre de ... vive en este hogar?",
    "NPCEP24A": "Núm. de orden",
    "NPCEP25": "25. ¿Cuál es o fue el nivel de educación más alto alcanzado por la madre de ... ?",
    "NPCEP25A": "Cuántos años aprobados:"
}


In [51]:
dictF = {
    "NPCFP1": "1. ¿ ... está afiliado(a) ( cotizante o beneficiario(a)) a alguna entidad de seguridad social en salud?",
    "NPCFP2": "2. ¿A cuál de los siguientes regímenes de seguridad social en salud está afiliado(a) ... ?",
    "NPCFP3": "3. ¿Por qué razón principal no está afiliado(a) a una entidad de seguridad social en salud?",
    "NPCFP4A": "4. ¿Quién paga MENSUALMENTE por la afiliación de ... ? 1. Paga una parte y otra la empresa o persona que lo(a) emplea",
    "NPCFP4B": "4. ¿Quién paga MENSUALMENTE por la afiliación de ... ? 2. Le descuentan de la pensión",
    "NPCFP4C": "4. ¿Quién paga MENSUALMENTE por la afiliación de ... ? 3. Paga la totalidad de la afiliación",
    "NPCFP4D": "4. ¿Quién paga MENSUALMENTE por la afiliación de ... ? 4. Paga completamente la empresa o persona que le emplea o empleó",
    "NPCFP4E": "4. ¿Quién paga MENSUALMENTE por la afiliación de ... ? 5. No paga, es beneficiario(a)",
    "NPCFP5": "5. ¿Cuánto paga o cuánto le descuentan MENSUALMENTE a ... para estar cubierto(a) por una entidad de seguridad social en salud?",
    "NPCFP7": "6. ¿ ... ha participado en acciones de promoción de salud y prevención de la enfermedad realizadas por la entidad de seguridad social en salud a la que está afiliado(a)?",
    "NPCFP8": "7. En general, considera que la calidad del servicio de la entidad de seguridad social en salud a la que ... está afiliado(a) es:",
    "NPCFP8A": "8. ¿Cuál es el aspecto que más influye en su percepción sobre la calidad del servicio de la entidad en la cual se encuentra afiliado?",
    "NPCFP8B": "9. ¿En los últimos 24 meses ... ha tenido que cambiar de EPS por sentirse insatisfecho con el servicio prestado?",
    "NPCFP9": "10. En promedio, ¿cuánto tiempo se demora en llegar ... desde su lugar de residencia a la IPS para sus consultas de medicina general? Minutos",
    "NPCFP10A": "11. ¿Cuáles de los siguientes planes o seguros complementarios tiene ... ? : 1. Póliza de hospitalización o cirugía",
    "NPCFP10B": "11. ¿Cuáles de los siguientes planes o seguros complementarios tiene ... ? : 2. Contrato de medicina prepagada",
    "NPCFP10C": "11. ¿Cuáles de los siguientes planes o seguros complementarios tiene ... ? : 3. Contrato de plan complementario de salud con una EPS",
    "NPCFP10D": "11. ¿Cuáles de los siguientes planes o seguros complementarios tiene ... ? : 4. Otro (seguro estudiantil, ambulancia, tarjeta de viajero, entre otros)",
    "NPCFP10E": "11. ¿Cuáles de los siguientes planes o seguros complementarios tiene ... ? : 5. Ninguno",
    "NPCFP11": "12. ¿Cuánto paga o le descuentan a ... por concepto de este o estos planes o seguros complementarios de salud?",
    "NPCFP11A": "Periodicidad:",
    "NPCFP12": "13. El estado de salud de ... en general es:",
    "NPCFP13A": "14. Sin estar enfermo(a) y por prevención, ¿ ... por lo menos una vez al año, consulta? 1. Medicina general",
    "NPCFP13B": "14. Sin estar enfermo(a) y por prevención, ¿ ... por lo menos una vez al año, consulta? 2. Medicina especializada",
    "NPCFP13C": "14. Sin estar enfermo(a) y por prevención, ¿ ... por lo menos una vez al año, consulta? 3. Odontología",
    "NPCFP13D": "14. Sin estar enfermo(a) y por prevención, ¿ ... por lo menos una vez al año, consulta? 4. Medicina alternativa",
    "NPCFP13E": "14. Sin estar enfermo(a) y por prevención, ¿ ... por lo menos una vez al año, consulta? 5. Ninguna de las anteriores",
    "NPCFP14A": "15. A... le han diagnosticado alguna de estas enfermedades o problemas de salud: 1. Enfermedades cardiovasculares, hipertensión?",
    "NPCFP14B": "15.A ... le han diagnosticado alguna de estas enfermedades o problemas de salud: 2. Enfermedades respiratorias, bronquitis, enfisema?",
    "NPCFP14C": "15. A... le han diagnosticado alguna de estas enfermedades o problemas de salud: 3. Insuficiencia renal?",
    "NPCFP14D": "15.A ... le han diagnosticado alguna de estas enfermedades o problemas de salud: 4. Enfermedades digestivas, úlcera gástrica?",
    "NPCFP14E": "15. A... le han diagnosticado alguna de estas enfermedades o problemas de salud: 5. Enfermedades de los huesos, lesiones, limitaciones del uso de los huesos, artrosis, artritis?",
    "NPCFP14F": "15. A... le han diagnosticado alguna de estas enfermedades o problemas de salud: 6. Diabetes?",
    "NPCFP14G": "15. A... le han diagnosticado alguna de estas enfermedades o problemas de salud: 7. Tumores malignos, cáncer?",
    "NPCFP14H": "15.A ... le han diagnosticado alguna de estas enfermedades o problemas de salud: 8. Enfermedades mentales, trastornos de la conciencia (depresión, ansiedad)?",
    "NPCFP14I": "15.A ... le han diagnosticado alguna de estas enfermedades o problemas de salud: 9. Asma?",
    "NPCFP14J": "15. A... le han diagnosticado alguna de estas enfermedades o problemas de salud: 10. Alergia crónica?",
    "NPCFP14K": "15.A ... le han diagnosticado alguna de estas enfermedades o problemas de salud: 11. Epilepsia?",
    "NPCFP14L": "15.A ... le han diagnosticado alguna de estas enfermedades o problemas de salud: 12. Trastornos de la conducta (hiperactividad etc.)?",
    "NPCFP15": "16. Para tratar esa(s) enfermedad(es) ¿ ... recibe atención médica periódica, asiste regularmente a una institución de salud o se hace controles?",
    "NPCFP16": "17. En los ÚLTIMOS 30 DÍAS, ¿ ... tuvo alguna enfermedad, accidente, problema odontológico o algún otro problema de salud que NO haya implicado hospitalización?",
    "NPCFP18": "18. Por este problema de salud, ¿durante cuántos días en total dejó ... de realizar sus actividades normales?",
    "NPCFP19": "19. ¿Qué hizo principalmente ... para tratar ese problema de salud?",
    "NPCFP20": "20. En general, considera que la calidad del servicio fue:",
    "NPCFP21A": "21. ... tiene alguna limitación permanente para: 1. Moverse o caminar",
    "NPCFP21B": "21. ... tiene alguna limitación permanente para: 2. Usar sus brazos o manos",
    "NPCFP21C": "21. ... tiene alguna limitación permanente para: 3. Ver, a pesar de usar lentes o gafas",
    "NPCFP21D": "21. ... tiene alguna limitación permanente para: 4. Oír, aún con aparatos especiales",
    "NPCFP21E": "21. ... tiene alguna limitación permanente para: 5. Hablar",
    "NPCFP21F": "21. ... tiene alguna limitación permanente para: 6. Entender o aprender",
    "NPCFP21G": "21. ... tiene alguna limitación permanente para: 7. Relacionarse con otras personas por problemas mentales o emocionales",
    "NPCFP21H": "21. ... tiene alguna limitación permanente para: 8. Bañarse, vestirse, alimentarse sin ayuda de alguién más",
    "NPCFP21I": "21. ... tiene alguna limitación permanente para: 9. Ninguna de las anteriores",
    "NPCFP22": "22. Para afrontar esta(s) limitación(es), ¿ ... sigue algún tratamiento médico?",
    "NPCFP23": "23. ¿Cómo afecta(n) esta(s) limitación(es) la capacidad de ... para trabajar, estudiar o realizar sus actividades cotidianas?",
    "NPCFP24": "24. ¿Quién se ocupa principalmente del cuidado de ... ?",
    "NPCFP24A": "Núm. de orden",
    "NPCFP24B": "2. Una persona de otro hogar, no remunerada. Esta persona es: 1 Hombre 2 Mujer",
    "NPCFP24C": "3. Una persona contratada para ayudarle Esta persona es: 1 Hombre 2 Mujer",
    "NPCFP25A": "25. ¿Quién asume el pago de la persona o de la institución que se encarga del cuidado de ... ? 1. El sistema de salud (Entidad Promotora de Salud (EPS), Entidad Promotora de Salud del régimen Subsidiado (EPS-S))",
    "NPCFP25B": "25. ¿Quién asume el pago de la persona o de la institución que se encarga del cuidado de ... ? 2. El hogar o la misma persona",
    "NPCFP25BA": "Gasto MENSUAL $",
    "NPCFP25C": "25. ¿Quién asume el pago de la persona o de la institución que se encarga del cuidado de ... ? 3. Familiar de otro hogar",
    "NPCFP25E": "25. ¿Quién asume el pago de la persona o de la institución que se encarga del cuidado de ... ? 4. Amigo(a)s o vecino(a)s",
    "NPCFP25F": "25. ¿Quién asume el pago de la persona o de la institución que se encarga del cuidado de ... ? 5. Otro",
    "NPCFP26": "26. Durante los ÚLTIMOS 12 MESES, ¿ ... tuvo que ser hospitalizado(a)?",
    "NPCFP26A": "¿Cuántas veces?",
    "NPCFP27": "27. Durante los ÚLTIMOS 12 MESES ¿Cuánto gastó el hogar en total por hospitalización(es) de ... ?",
    "NPCFP29": "28. Considera que la calidad del servicio de su última o única hospitalización fue:",
    "NPCFP30": "29. Durante los ÚLTIMOS 30 DÍAS, ¿ ... acudió a un servicio de urgencias?",
    "NPCFP31": "30. ¿ ... recibió atención médica de urgencias?",
    "NPCFP32": "31. ¿Cuánto tiempo transcurrió entre el momento de llegar al servicio de urgencias y el momento de ser atendido por personal médico?",
    "NPCFP33A": "32. Durante los ÚLTIMOS 30 DÍAS, ... utilizó servicios de salud para: 1. Consulta de medicina general?",
    "NPCFP33AA": "¿Cuánto gastó el hogar en la consulta?",
    "NPCFP33B": "32. Durante los ÚLTIMOS 30 DÍAS, ... utilizó servicios de salud para: 2. Consulta médica con especialista?",
    "NPCFP33BA": "¿Cuánto gastó el hogar en la consulta?",
    "NPCFP33C": "32. Durante los ÚLTIMOS 30 DÍAS, ... utilizó servicios de salud para: 3. Consulta o tratamiento odontológico?",
    "NPCFP33CA": "¿Cuánto gastó el hogar por la consulta o tratamiento?",
    "NPCFP33D": "32. Durante los ÚLTIMOS 30 DÍAS, ... utilizó servicios de salud para: 4. Vacunas?",
    "NPCFP33DA": "¿Cuánto gastó el hogar por la(s) vacuna(s)?",
    "NPCFP33E": "32. Durante los ÚLTIMOS 30 DÍAS, ... utilizó servicios de salud para: 5. Laboratorio clínico, RX, exámenes de diagnóstico?",
    "NPCFP33EA": "¿Cuánto gastó el hogar por esos servicios?",
    "NPCFP33F": "32. Durante los ÚLTIMOS 30 DÍAS, ... utilizó servicios de salud para: 6. Terapias alternativas (hemoterapia, acupuntura, esencias florales, musicoterapia)?",
    "NPCFP33FA": "¿Cuánto gastó el hogar en esos servicios?",
    "NPCFP34": "33. Durante los ÚLTIMOS 30 DÍAS, ¿cuánto gastó el hogar en medicamentos para ... ?",
    "NPCFP35A": "34. Durante los ÚLTIMOS 12 MESES ¿para ... el hogar tuvo gastos por: 1. Lentes, audífonos o aparatos ortopédicos (muletas, sillas de ruedas, entre otros)?",
    "NPCFP35AA": "Valor $",
    "NPCFP35B": "34. Durante los ÚLTIMOS 12 MESES ¿para ... el hogar tuvo gastos por: 2. Cirugías o procedimientos quirúrgicos ambulatorios (incluya cuota moderadora, copago y gastos por consulta médica, exámenes y medicamentos)?",
    "NPCFP35BA": "Valor $",
    "NPCFP36": "35. En los ÚLTIMOS 30 DÍAS, ¿cuántas veces por semana ... practicó deporte o realizó actividad física por 30 minutos continuos o más?",
    "NPCFP37": "36. ¿Cuál fue la razón principal para que ... no practicara deporte ni tuviera actividad física en los ÚLTIMOS 30 DÍAS?",
    "NPCFP38": "37. ¿ ... ha fumado al menos un cigarrillo en los ÚLTIMOS 30 DÍAS?",
    "NPCFP39": "38. ¿ ... fuma todos los días?",
    "NPCFP39A": "¿Cuántos cigarrillos al día?",
    "NPCFP40A": "39. Durante los ÚLTIMOS 12 MESES, ¿a ... le han practicado los siguientes exámenes o procedimientos? 1. Citología vaginal (mujeres de 15 años y más)",
    "NPCFP40B": "39. Durante los ÚLTIMOS 12 MESES, ¿a ... le han practicado los siguientes exámenes o procedimientos? 2. Mamografía (mujeres de 40 años y más)",
    "NPCFP40C": "39. Durante los ÚLTIMOS 12 MESES, ¿a ... le han practicado los siguientes exámenes o procedimientos? 3. Exámenes de próstata (hombres de 40 años y más)",
    "NPCFP40D": "39. Durante los ÚLTIMOS 12 MESES, ¿a ... le han practicado los siguientes exámenes o procedimientos? 4. Toma de tensión arterial",
    "NPCFP40E": "39. Durante los ÚLTIMOS 12 MESES, ¿a ... le han practicado los siguientes exámenes o procedimientos? 5. Exámen V.I.H.",
    "NPCFP40F": "39. Durante los ÚLTIMOS 12 MESES, ¿a ... le han practicado los siguientes exámenes o procedimientos? 6. Exámenes de triglicéridos, colesterol, glucosa (personas de 15 años y más)",
    "NPCFP40": "40. ¿ ... está embarazada actualmente o ha tenido hijos?",
    "NPCFP41": "41. Si está embarazada actualmente, ¿asiste a control prenatal?",
    "NPCFP42": "42. Durante este embarazo ha consumido suplementos vitamínicos (sulfato ferroso, ácido fólico, calcio, etc.)?",
    "NPCFP43": "43. ¿A qué edad tuvo su primer hijo?",
    "NPCFP43A": "Edad",
    "NPCFP44": "44. ¿... conoce o ha oído hablar de algún método para prevenir o postergar el embarazo?",
    "NPCFP45": "45. ¿Usted o su pareja usa algún método anticonceptivo para prevenir o postergar un embarazo?"
}


In [66]:
textoC = obtener_columnas_ordenadas21(dictC, columnas_ordenadas21["C"])

In [69]:
textoF = obtener_columnas_ordenadas21(dictF, columnas_ordenadas21["F"])

In [76]:
dictH = {
    "NPCHP1": "1. ¿ ...sabe leer y escribir?",
    "NPCHP2": "2. ¿ ...actualmente estudia (asiste al preescolar, escuela, colegio, o universidad)?",
    "NPCHP3": "3. ¿Cuál es la principal razón para que ...no estudie?",
    "NPCHP4": "4. ¿Cuál es el nivel educativo más alto alcanzado por ... y el último año o grado aprobado en este nivel?",
    "NPCHP4A": "Último año o grado aprobado",
    "NPCHP5": "5. ¿Cuántos años de estudios superiores (técnicos, tecnológicos, universitarios, de posgrado, etc.) ha realizado y aprobado?",
    "NPCHP6": "6. ¿En qué nivel está matriculado(a) ...y qué grado o año cursa?",
    "NPCHP6A": "Grado o año que cursa:",
    "NPCHP7": "7. ¿Cuántos años de estudios superiores (técnicos, tecnológicos, universitarios, de posgrado, etc.) ha realizado y aprobado?",
    "NPCHP9A": "8. ¿… es beneficiario/a de alguno de los siguientes programas o subsidios?: 1. Transporte en rutas de la Secretaría de Educación del Distrito (solo para Bogotá)",
    "NPCHP9B": "8. ¿… es beneficiario/a de alguno de los siguientes programas o subsidios?: 2. Subsidio educativo en dinero de Familias en Acción",
    "NPCHP9C": "8. ¿… es beneficiario/a de alguno de los siguientes programas o subsidios?: 3. Subsidio educativo de la alcaldía",
    "NPCHP9D": "8. ¿… es beneficiario/a de alguno de los siguientes programas o subsidios?: 4. Subsidio de transporte de la alcaldía",
    "NPCHP9E": "8. ¿ ...es beneficiario(a) de alguno de los siguientes programas o subsidios?: 5. Subsidio educativo de la Gobernación de Cundinamarca",
    "NPCHP10": "9. ¿Este hogar paga por ...pensión en el establecimiento educativo?",
    "NPCHP10A": "Valor MENSUAL pagado",
    "NPCHP11": "10. ¿Este hogar tiene que pagar por transporte escolar para ...?",
    "NPCHP11A": "Valor MENSUAL pagado",
    "NPCHP12": "11. El establecimiento donde estudia ...es:",
    "NPCHP12A": "No oficial (con subsidio del estado o sin subsidio)",
    "NPCHP13": "12. El establecimiento donde ...estudia está ubicado en:",
    "NPCHP13A": "Departamento",
    "NPCHP13B": "Municipio",
    "NPCHP14": "13. ¿En qué localidad esta ubicado?",
    "NPCHP16": "15. El establecimiento educativo está ubicado en:",
    "NPCHP17": "16. ¿Principalmente en cual jornada estudia?",
    "NPCHP18AA": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Transmilenio?",
    "NPCHP18AB": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Buses del SITP?",
    "NPCHP18AC": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Bus buseta o colectivo?",
    "NPCHP18AD": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Automóvil de uso particular?",
    "NPCHP18AE": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Taxi?",
    "NPCHP18AF": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Motocicleta?",
    "NPCHP18AG": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Bicicleta?",
    "NPCHP18AH": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Ruta escolar ?",
    "NPCHP18AI": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: A pie?",
    "NPCHP18AI1": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Bus intermunicipal?",
    "NPCHP18AJ": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Bicitaxi o mototaxi?",
    "NPCHP18AK": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Transporte en vehículos particulares a través de plataformas o aplicaciones?",
    "NPCHP18AL": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Vehículo, patineta, bicicleta o moto eléctricos?",
    "NPCHP18AM": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Caballo? (solo para municipios y Bogotá rural)",
    "NPCHP18AN": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: Otro?",
    "NPCHP18AO": "17. En un trayecto normal a su sitio de estudio, ¿cuáles medios de transporte utiliza …: No se desplaza",
    "NPCHP19": "18. ¿Cuánto tiempo se demora … en su viaje de ida a su sitio de estudio (incluya tiempo de espera del medio de transporte y el tiempo en todos los medios utilizados)? Minutos",
    "NPCHP20": "19. ¿Recibe ...en el establecimiento educativo, alimentos (desayunos, medias nueves, refrigerios, almuerzos, etc.) en forma gratuita o por un pago simbólico?",
    "NPCHP20A": "Valor DIARIO pagado",
    "NPCHP20B": "Valor DIARIO estimado",
    "NPCHP21A": "20. Durante ESTE AÑO escolar, ¿el hogar pagó: 1. Matrícula para ...?",
    "NPCHP21AA": "Valor pagado",
    "NPCHP21B": "20. Durante ESTE AÑO escolar, ¿el hogar pagó: 2. Libros, útiles escolares, uniformes y elementos de aseo para ...?",
    "NPCHP21BA": "Valor pagado",
    "NPCHP21C": "20. Durante ESTE AÑO escolar, ¿el hogar pagó: 3. Mantenimiento de equipos, aula virtual, sistematización de calificaciones para ...?",
    "NPCHP21CA": "Valor pagado",
    "NPCHP21D": "20. Durante ESTE AÑO escolar, ¿el hogar pagó: 4. Cursos o actividades complementarias dentro del establecimiento educativo (artísticas, deportivas) para ...?",
    "NPCHP21DA": "Valor pagado",
    "NPCHP22": "21. ¿El MES PASADO el hogar gastó en útiles (papel, lápices, cuadernos, etc.), material escolar o fotocopias para ...?",
    "NPCHP22A": "Valor",
    "NPCHP23": "22. Durante ESTE AÑO ¿el hogar realizó otros pagos como: rifas, bingos, salidas pedagógicas o de campo, etc. en el establecimiento educativo para ...?",
    "NPCHP23A": "Valor",
    "NPCHP24": "23. Durante este AÑO escolar, ¿ ...recibió subsidio o beca en dinero o en especie para estudiar?",
    "NPCHP24_1": "23. Durante este AÑO escolar, ¿ ...recibió subsidio o beca en dinero o en especie para estudiar? Sí, en dinero",
    "NPCHP24AA": "En dinero valor",
    "NPCHP24AB": "En Dinero Frecuencia:",
    "NPCHP24_2": "23. Durante este AÑO escolar, ¿ ...recibió subsidio o beca en dinero o en especie para estudiar? Sí, en Especie",
    "NPCHP24BA": "En Especie valor estimado",
    "NPCHP24BB": "En especie frecuencia:",
    "NPCHP25A": "24. ¿De quién(es) recibió el subsidio o la beca para estudiar? 1. Del mismo establecimiento educativo",
    "NPCHP25B": "24. ¿De quién(es) recibió el subsidio o la beca para estudiar? 2. Del gobierno nacional",
    "NPCHP25C": "24. ¿De quién(es) recibió el subsidio o la beca para estudiar? 3. Del gobierno departamental",
    "NPCHP25D": "24. ¿De quién(es) recibió el subsidio o la beca para estudiar? 4. Del gobierno distrital o municipal",
    "NPCHP25E": "24. ¿De quién(es) recibió el subsidio o la beca para estudiar? 5. Del ICETEX",
    "NPCHP25F": "24. ¿De quién(es) recibió el subsidio o la beca para estudiar? 6. De otra entidad pública",
    "NPCHP25G": "24. ¿De quién(es) recibió el subsidio o la beca para estudiar? 7. De la empresa pública donde usted o un/a familiar trabajan",
    "NPCHP25H": "24. ¿De quién(es) recibió el subsidio o la beca para estudiar? 8. De la empresa privada donde usted o un/a familiar trabajan",
    "NPCHP25I": "24. ¿De quién(es) recibió el subsidio o la beca para estudiar? 9. De la caja de compensación familiar",
    "NPCHP25J": "24. ¿De quién(es) recibió el subsidio o la beca para estudiar? 10. De otra entidad privada",
    "NPCHP28": "25. Durante este AÑO ESCOLAR, ¿ ...ha recibido crédito educativo?",
    "NPCHP28A": "Valor",
    "NPCHP28B": "Frecuencia:",
    "NPCHP29A": "26. ¿De quién(es) recibió ...el crédito educativo? 1. Del mismo establecimiento educativo",
    "NPCHP29B": "26. ¿De quién(es) recibió ...el crédito educativo? 2. Del ICETEX",
    "NPCHP29C": "26. ¿De quién(es) recibió ...el crédito educativo? 3. De un banco o corporación",
    "NPCHP29D": "26. ¿De quién(es) recibió ...el crédito educativo? 4. Del gobierno distrital o municipal",
    "NPCHP29E": "26. ¿De quién(es) recibió ...el crédito educativo? 5. De otra entidad pública",
    "NPCHP29F": "26. ¿De quién(es) recibió ...el crédito educativo? 6. De la empresa pública donde usted o un/a familiar trabajan",
    "NPCHP29G": "26. ¿De quién(es) recibió ...el crédito educativo? 7. De la empresa privada donde usted o un/a familiar trabajan",
    "NPCHP29H": "26. ¿De quién(es) recibió ...el crédito educativo? 8. De un/a familiar",
    "NPCHP29I": "26. ¿De quién(es) recibió ...el crédito educativo? 9. De otra entidad",
    "NPCHP30A": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 1. Fue a la ciclovía",
    "NPCHP30B": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 2. Asistió a eventos deportivos",
    "NPCHP30C": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 3. Asistió a espectáculos de teatro, danza, música en vivo",
    "NPCHP30D": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 4. Asistió a exposiciones de arte o museos",
    "NPCHP30E": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 5. Asistió a bibliotecas",
    "NPCHP30F": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 6. Fue a cine",
    "NPCHP30G": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 7. Leyó libros",
    "NPCHP30H": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 8. Fue a fiestas, discotecas",
    "NPCHP30I": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 9. Salió a comer con amigos o familiares",
    "NPCHP30J": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 10. Fue a zonas verdes o parques públicos de acceso libre y gratuito",
    "NPCHP30K": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 11. Visitó parques de diversión o centros interactivos (como Maloka, Salitre mágico, Jaime Duque, etc)",
    "NPCHP30L": "27. En su tiempo libre, ¿cuáles de las siguientes actividades realizó ...en los ÚLTIMOS TREINTA DÍAS? 12. Pasear o caminar",
    "NPCHP31AA": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó a: 1. Ver televisión? Lunes a Viernes Horas:",
    "NPCHP31AB": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó a: 1. Ver televisión? Sábado a Domingo Horas:",
    "NPCHP31BA": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 2. Jugar video juegos, chatear o navegar en internet por diversión? Lunes a Viernes Horas:",
    "NPCHP31BB": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 2. Jugar video juegos, chatear o navegar en internet por diversión? Sábado a Domingo Horas:",
    "NPCHP31CA": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 3. Dormir? Lunes a Viernes Horas:",
    "NPCHP31CB": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 3. Dormir? Sábado a domingo Horas:",
    "NPCHP31DA": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 4. Actividades de refuerzo académico Lunes a Viernes Horas:",
    "NPCHP31DB": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 4. Actividades de refuerzo académico Sábado a domingo Horas:",
    "NPCHP31DA_1": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 5. Actividades artísticas? Lunes a Viernes Horas:",
    "NPCHP31DB_1": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 5. Actividades artísticas? Sábado a domingo Horas:",
    "NPCHP31GA": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 6. Actividades deportivas o de ejercicio físico? Lunes a Viernes Horas:",
    "NPCHP31GB": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 6. Actividades deportivas o de ejercicio físico? Sábado a domingo Horas:",
    "NPCHP31DA_2": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 7. Leer libros, revistas, periódicos, blogs, foros (impreso o digital) Lunes a Viernes Horas:",
    "NPCHP31DB_2": "28. Durante la SEMANA PASADA, ¿cuántas horas dedicó ... a: 7. Leer libros, revistas, periódicos, blogs, foros (impreso o digital) Sábado a domingo Horas:",
    "NPCHP32": "29. ¿Con quién permanece ...después de asistir al establecimiento educativo o durante la mayor parte del tiempo entre semana?",
    "NPCHP32B": "Una persona de otro hogar",
    "NPCHP32A": "Una persona de este hogar Núm. de orden",
    "NPCHP33": "30. ¿Cuántos años tiene esta persona?",
    "NPCHP34": "31. ¿Cuál es el nivel educativo de esta persona?",
    "NPCHP35A": "32. Durante el PRESENTE AÑO, … ha sido discriminado/a, molestado/a, o le han hecho sentir mal por alguno de los siguientes motivos: 1. Por su raza u origen étnico",
    "NPCHP35B": "32. Durante el PRESENTE AÑO, … ha sido discriminado/a, molestado/a, o le han hecho sentir mal por alguno de los siguientes motivos: 2. Por ser hombre o mujer",
    "NPCHP35C": "32. Durante el PRESENTE AÑO, … ha sido discriminado/a, molestado/a, o le han hecho sentir mal por alguno de los siguientes motivos: 3. Por ser de los sectores LGBTI",
    "NPCHP35D": "32. Durante el PRESENTE AÑO, … ha sido discriminado/a, molestado/a, o le han hecho sentir mal por alguno de los siguientes motivos: 4. Por sus creencias religiosas",
    "NPCHP35E": "32. Durante el PRESENTE AÑO, … ha sido discriminado/a, molestado/a, o le han hecho sentir mal por alguno de los siguientes motivos: 5. Por su peso, tamaño o apariencia física",
    "NPCHP35F": "32. Durante el PRESENTE AÑO, … ha sido discriminado/a, molestado/a, o le han hecho sentir mal por alguno de los siguientes motivos: 6. Por sentirse identificado con algún grupo como metaleros, skinhead, emos, entre otros",
    "NPCHP35I": "32. Durante el PRESENTE AÑO, … ha sido discriminado/a, molestado/a, o le han hecho sentir mal por alguno de los siguientes motivos: 7. Por su condición económica y social",
    "NPCHP35J": "32. Durante el PRESENTE AÑO, … ha sido discriminado/a, molestado/a, o le han hecho sentir mal por alguno de los siguientes motivos: 8. Por su origen campesino",
    "NPCHP35K": "32. Durante el PRESENTE AÑO, … ha sido discriminado/a, molestado/a, o le han hecho sentir mal por alguno de los siguientes motivos: 9. Por ser extranjero",
    "NPCHP36": "33. ¿En los ÚLTIMOS 12 MESES ha tomado cursos virtuales (on-line) a través de internet (Open English, NextU, SENA virtual, entre otros)?",
    "NPCHP36A": "¿Cuánto pagó por estos cursos en los ÚLTIMOS 12 MESES?",
    "NPCHP37": "34. En comparación a la formación que normalmente recibía antes de las medidas tomadas por efecto de la pandemia del coronavirus (COVID-19), ¿considera que la calidad de la educación en el año 2020?:"

}



In [77]:
textoH = obtener_columnas_ordenadas21(dictH, columnas_ordenadas21["H"])


In [78]:
print(textoH)

{'NPCHP2': '2. ¿ ...actualmente estudia (asiste al preescolar, escuela, colegio, o universidad)?', 'NPCHP3': '3. ¿Cuál es la principal razón para que ...no estudie?', 'NPCHP4': '4. ¿Cuál es el nivel educativo más alto alcanzado por ... y el último año o grado aprobado en este nivel?', 'NPCHP4A': 'Último año o grado aprobado', 'NPCHP5': '5. ¿Cuántos años de estudios superiores (técnicos, tecnológicos, universitarios, de posgrado, etc.) ha realizado y aprobado?', 'NPCHP6': '6. ¿En qué nivel está matriculado(a) ...y qué grado o año cursa?', 'NPCHP6A': 'Grado o año que cursa:', 'NPCHP7': '7. ¿Cuántos años de estudios superiores (técnicos, tecnológicos, universitarios, de posgrado, etc.) ha realizado y aprobado?', 'NPCHP10': '9. ¿Este hogar paga por ...pensión en el establecimiento educativo?', 'NPCHP10A': 'Valor MENSUAL pagado', 'NPCHP11A': 'Valor MENSUAL pagado', 'NPCHP12': '11. El establecimiento donde estudia ...es:', 'NPCHP13A': 'Departamento', 'NPCHP13B': 'Municipio', 'NPCHP14': '13. 

In [123]:
# Organizar la información de los diccionarios. Cada pregunta tiene el formato "NPCFP1A", donde los tres primeros digitos
# representan un ID, la letra continua la categoría, luego "P#" representa el numero de la pregunta y las letras continuas
# (en caso de que las haya porque no siempre hay) representan las subpreguntas. 
# Se debe organizar la información de tal manera que se pueda acceder a la información de cada pregunta general de manera sencilla.
# Diccionario de preguntas cuyos valores son subpreguntas

def organize_questions(dictionary):
    # Create a dictionary to store the questions
    questions = {}
    
    # Iterate over the keys in the input dictionary
    for key in dictionary:
        # Extract the digits from the key
        digits = ''.join(filter(str.isdigit, key))
        
        # Initialize question_id with a default value
        question_id = digits

        # Add the question to the dictionary if it doesn't exist
        if question_id is not None and question_id not in questions:
            questions[question_id] = dictionary[key]
    
    return questions




dict_keys(['1', '2', '3', '4', '5', '6', '7', '81', '82', '83', '84', '85', '86', '87', '88', '89', '810', '9', '10', '11', '12', '13', '14', '15', '19', '20', '22', '23', '24', '25', '26', '27', '28', '29', '31', '32', '33', '34', '35', '36', '37', '38', '39', '393', '399', '40', '41', '42', '44', '45', '46', '47', '471'])


In [ ]:
# Imprimir las preguntas de cada sección
def print_questions(questions):
    # Iterate over the questions
    for question in questions:
        # Print the question followed by a new line
        print(question, '\n')

for i in columnas_ordenadas21:
    if i != "otros":
        print_questions(organize_questions(columnas_ordenadas21[i]))


dict_keys(['1', '2', '3', '4', '5', '6', '7', '81', '82', '83', '84', '85', '86', '87', '88', '89', '810', '9', '10', '11', '12', '13', '14', '15', '19', '20', '22', '23', '24', '25', '26', '27', '28', '29', '31', '32', '33', '34', '35', '36', '37', '38', '39', '393', '399', '40', '41', '42', '44', '45', '46', '47', '471'])


In [119]:
dictPrueba = organize_questions(dictC)
print(dictPrueba)

UnboundLocalError: local variable 'question_id' referenced before assignment

{'810': '8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 10. Otra', '393': '36. ¿Cuáles de las siguientes prácticas realiza este hogar para reducir el consumo de agua y energía eléctrica?: 3. Planchar la mayor cantidad de ropa en cada ocasión o no planchar', '399': '36. ¿Cuáles de las siguientes prácticas realiza este hogar para reducir el consumo de agua y energía eléctrica?: 9. Instalaron accesorios ahorradores de agua en duchas, lavamanos y lavaplatos', '471': '43. ¿En este hogar tienen mascotas que vivan permanentemente con los miembros del hogar? 1. Perros ¿Cuántos?'}


In [ ]:
""""
    NHCCP5": "5. Si fuera a comprar esta vivienda ahora, ¿cuánto cree que tendría que pagar?",
    "NHCCP6": "6. ¿Cuál fue el año de compra de la vivienda o del lote o terreno?",
    "NHCCP7": "7. ¿Cuál fue el valor de la compra?",
    "NHCCP8_1": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 1. Crédito bancario hipotecario",
    "NHCCP8_2": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 2. Crédito bancario diferente a hipotecario",
    "NHCCP8_3": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 3. Crédito con el Fondo Nacional deI Ahorro",
    "NHCCP8_4": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 4. Crédito con cooperativas o fondos de empleados",
    "NHCCP8_5": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 5. Crédito con fondos de vivienda o cajas de vivienda",
    "NHCCP8_6": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 6. Préstamos de amigos o familiares",
    "NHCCP8_7": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 7. Cesantías",
    "NHCCP8_8": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 8. Recursos propios o ahorros",
    "NHCCP8_9": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 9. Subsidios",
    "NHCCP8_10": "8. ¿Cuáles de las siguientes fuentes de financiamiento utilizaron para la compra o construcción de esta vivienda (incluida la compra del lote)?: 10. Otra",
    "NHCCP9": "9. Si tuviera que pagar arriendo por esta vivienda, ¿cuánto cree que sería el monto MENSUAL?",
    "NHCCP10": "10. ¿Cuánto paga MENSUALMENTE por el arriendo o leasing de esta vivienda?",
    "NHCCP10A": "10a. ¿Cuenta con contrato escrito de arrendamiento?",
    "NHCCP10B": "10b. ¿A raíz de las medidas tomadas por la pandemia del coronavirus (Covid-19), entre marzo de 2020 y el momento actual: 1. Se atrasó o dejo de pagar alguna cuota de arrendamiento?",
    "NHCCP10C": "¿
    
    """

In [91]:
textoPrueba = organizar_diccionario(dictC)
print(textoPrueba)

{'NHC': {'C': {'P': '43. ¿En este hogar tienen mascotas que vivan permanentemente con los miembros del hogar? 3. Otros'}}}


{'NVCBP': ['NVCBP1', 'NVCBP2', 'NVCBP3', 'NVCBP4', 'NVCBP5', 'NVCBP6', 'NVCBP7', 'NVCBP8A', 'NVCBP8B', 'NVCBP8C', 'NVCBP9', 'NVCBP9A1', 'NVCBP9A2', 'NVCBP9A3', 'NVCBP10', 'NVCBP11AA', 'NVCBP13', 'NVCBP14A', 'NVCBP14B', 'NVCBP14E', 'NVCBP14F', 'NVCBP14G', 'NVCBP14I', 'NVCBP14K', 'NVCBP15A', 'NVCBP15B', 'NVCBP15C', 'NVCBP15D', 'NVCBP15E', 'NVCBP15F', 'NVCBP15G', 'NVCBP15H', 'NVCBP15I', 'NVCBP15J', 'NVCBP16A1', 'NVCBP16A2', 'NVCBP16A3', 'NVCBP16A4']}
